name: CI

# trigger
on:
  pull_request:
  push:
    branches:
    - main
  schedule:
    # run Tuesday at noon UTC
    - cron: '0 13 * * 2'

jobs:
  base:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
        - os: ubuntu-latest
          path: ~/.cache/pip
        - os: macos-latest
          path: ~/Library/Caches/pip
        - os: windows-latest
          path: ~\AppData\Local\pip\Cache
        python-version: ['3.10', '3.11']
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Prepare python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache
      uses: actions/cache@v2
      with:
        path: ${{ matrix.path }}
        key: ci-base-${{ runner.os }}-${{ matrix.python-version }}

    - name: Install tox
      run: pip install tox

    - name: Run tests
      run: tox

    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml

  notebooks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Prepare python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ci-notebooks-${{ runner.os }}-${{ matrix.python-version }}

    - name: Install dependencies
      run: .github/workflows/install_deps.sh amici

    - name: Test notebooks
      run: tox -e notebooks
      timeout-minutes: 60

  doc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']


    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Prepare python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ci-doc-${{ runner.os }}-${{ matrix.python-version }}

    - name: Install dependencies
      run: .github/workflows/install_deps.sh doc

    - name: Test documentation build
      run: tox -e doc

